version: '3'

services:
  db:
    image: postgres
    platform: 'linux/x86_64'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  mq:
    image: rabbitmq:3-management
    platform: 'linux/x86_64'
    ports:
      - 15672:15672

  worker:
    platform: 'linux/x86_64'
    build:
      context: .
      args:
        RUNENV: local
    command: bash -c "celery -A config.celery -b amqp://guest@mq/ worker --loglevel=info -Q packages,db,git,default,periodic,pipeline"
    depends_on:
      - mq
    links:
      - db
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/code
      - ./data:/data

  beat:
    platform: 'linux/x86_64'
    build:
      context: .
      args:
        RUNENV: local
    command: bash -c "celery -A config.celery beat --loglevel debug"
    volumes:
      - .:/code
      - ./data:/data

  web:
    platform: 'linux/x86_64'
    build:
      context: .
      args:
        RUNENV: local
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - mq
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 8000:8000
    volumes:
      - .:/code
