version: '3'

services:
  worker:
    build:
      context: .
      args:
        RUNENV: celery-production
    environment:
      DATABASE_URL: {{ DATABASE_URL }}
    user: 1000:1000
    command: >
      sh -c "celery worker \
        -A config.celery \
        -b {{ RABBITMQ_URL }} \
        -Q packages,git \
        --hostname=worker01@infrastructure.qiime2.org"
    volumes:
      - /usr/share/nginx/html/packages.qiime2.org/:/data

  beat:
    build:
      context: .
      args:
        RUNENV: celery-production
    user: 1000:1000
    command: sh -c "celery beat -A config.celery -b {{ RABBITMQ_URL }}"
    volumes:
      - /usr/share/nginx/html/packages.qiime2.org/:/data
